# TP5: Initiation à la recherche opérationnelle

La *recherche opérationnelle* est un domaine se situant à l'intersection entre mathématiques appliquées, informatique et économie, qui a pour but de résoudre des problèmes d'optimisation dans diverses situations: combinatoire, aléatoire ou concurrentiel (lorsque nos propres actions influent les réactions des autres).

Dans le cadre de cette initiation, nous allons nous concentrer principalement sur des problèmes combinatoires. 

Pour ce premier TP, nous verrons plusieurs types de problème classiques en recherche opérationnelle dans un cadre combiantoire.

## 1. Outils de Bases

#### Les graphes non-orientés

Un graphe pondéré $G$ est la donnée $(V,E,\omega)$ où $V$ est l'ensemble des *sommets* de $G$, $E$ est l'ensemble des *arêtes* et $\omega:E \rightarrow \mathbb{N}$ est la fonction qui associe à une arête son *poids*. 

![image](graphe_poids.png)

Un tel graphe peut-être interprété comme un problème concrêt. Par exemple, les sommets peuvent correspondre à des villes, les arêtes peuvent correspondre à des routes et les poids associés peuvent représenter des distances ou des coûts de voyage.

Pour représenter un tel graphe, nous allons utiliser sa *matrice d'adjacence*. La matrice d'adjacence du graphe ci dessus est:
$$
\begin{array}{c|ccccccc}
  & A & B & C  & D & E & F & G \\
A & 0 & 4 & 0  & 0 & 6 & 0 & 0 \\
B & 4 & 0 & 2  & 3 & 0 & 0 & 0 \\
C & 0 & 2 & 0  &11 & 0 & 0 & 0 \\
D & 0 & 3 &11  & 0 & 7 & 0 & 0 \\
E & 6 & 0 & 0  & 7 & 0 & 7 & 4 \\
F & 0 & 0 & 0  & 0 & 7 & 0 & 5 \\
G & 0 & 0 & 0  & 0 & 4 & 5 & 0
\end{array}
$$

A la $i$-ème ligne et colonne $j$ figure le poids de l'arête allant de $i$ à $j$. Comme le graphe est non-orienté, la matrice d'adjacence du graphe est *symétrique*.

Un dit qu'un sommet $y$ est *voisin* d'un sommet $x$, s'il existe une arête entre ces deux sommets.

**TODO**: grâce à la bibliothèque *numpy* coder la matrice d'adjacence de la matrice ci-dessus.


In [1]:
import numpy as np
pass

#### Les arbres pondérés

Un *arbre pondéré* est un graphe pondéré bien particulier. Il vérifie les deux propriétés suivantes:
- il est *connexe*, c'est-à-dire que toute paire de sommet $(x,y)$ il existe un chemin de $x$ vers $y$;
- il est *sans boucle*, c'est-à-dire que tout chemin du graphe ne passent pas deux fois par le même sommet.

**TODO:** Coder une fonction *voisins(A,j)* qui renvoie les voisins du $j$-ème sommet du graphe de matrice d'adjacence $A$. 

In [3]:
def voisins(A,j):
    pass

In [5]:
voisins(A,3)

NameError: name 'A' is not defined

**TODO**: Coder une fonction *is_tree(A)* qui vérifie si la matrice d'adjacence du graphe $A$ correspond à la la matrice d'adjacence d'un arbre.

Donné généreusement ici.

In [7]:
def is_tree(A):
    Visited={0}
    current_place=0
    n=len(A)
    cpt=0
    for v in range(n):
        for x in voisins(A,v):
            Visited=Visited| {x}
            cpt=cpt+1
    # Si Visited contient toutes les colonnes cela signifie que le graphe est connexe.
    if cpt/2==n-1:
        if Visited=={i for i in range(n)}:
            return True
    return False

In [8]:
is_tree(A)

False

In [9]:
B=np.array([[0,1,0,1],[1,0,1,0],[0,1,0,0],[1,0,0,0]])
B

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [10]:
is_tree(B)

True

**TODO**: écrire une fonction *poids_total(A)* qui calcule le poids total d'un graphe via sa matrice d'adjacence $A$. 

Donné généreusement ici.

In [14]:
def poids_total(A):
    sum=0
    n=len(A)
    for i in range(n):
        for j in range(n):
            sum=sum+A[i,j]
    return sum/2 #car on compte deux fois les arêtes dans le cas non-orienté

In [20]:
poids_total(A)

49.0

## 1.2. Cas particulier des graphes orientés


Un graphe orienté pondéré $G$ est la donnée $(V,E,\omega)$ où $V$ est l'ensemble des *sommets* de $G$, $E$ est l'ensemble des *arcs* et $\omega:E \rightarrow \mathbb{N}$ est la fonction qui associe à une arête son *poids*. 

![image](graphe_oriented.png)

Un tel graphe peut-être interprété comme un problème concrêt. Par exemple, les sommets peuvent correspondre à des villes, les arêtes peuvent correspondre à des routes et les poids associés peuvent représenter des distances ou des coûts de voyage.

Pour représenter un tel graphe, nous allons utiliser sa *matrice d'adjacence*. La matrice d'adjacence du graphe ci dessus est:
$$
\begin{array}{c|ccccccc}
  & 1 & 2 & 3  & 4 & 5 & 6 & 7 \\
1 & 0 & 5 & 0  & 3 & 12 & 5 & 0 \\
2 & 0 & 0 & 0  & 1 & 0 & 0 & 0 \\
3 & 0 & 0 & 0  & 0 & 0 & 16 & 0 \\
4 & 0 & 0 & 0  & 0 & 1 & 0 & 1 \\
5 & 0 & 0 & 1  & 0 & 0 & 2 & 0 \\
6 & 0 & 0 & 0  & 0 & 0 & 0 & 0 \\
7 & 0 & 0 & 0  & 0 & 0 & 0 & 0
\end{array}
$$
Le coefficient ligne $i$ colonne $j$ représente le poids de l'arête $(i,j)$.

**TODO**: dans le cas des graphes orientés pondérés, écrire des fonctions *prev_or* et *next_or* qui donne les prédecesseurs et les successeurs du point passé en argument, *is_tree_or* qui donne si le graphe orienté est une arborescence et *poids_total_or* renvoyant le poids total du graphe.

In [19]:
def prev_or(A,j):
    pass
    
def succ_or(A,j):
    pass

def is_tree_or(A):
    pass
    
def poids_total_or(A):
    pass

In [28]:
prev_or(B,0)

[]

In [30]:
succ_or(B,0)

[1, 3, 4, 5]

In [33]:
is_tree_or(T)

True

In [35]:
poids_total_or(B)

47

## 1.4. Difficultés

En réalité, l'algorithme glouton ne donne pas la meilleure solution pour les problèmes du voyageur de commerce et du sac à dos.
En revanche, il donne toujours la solution optimale pour le problème de l'arbre couvrant minimal et cet algorithme porte alors le nom d'algorithme de *Kruskal*.

Remarquons qu'une méthode gloutonne n'est pas très efficace sur la recherche de l'algorithme de plus court chemin. Un algorithme plus efficace comme celui de *Dijkstra* est à privilégier dans ce cas.

# 2. La programmation linéaire

Un problème de *programmation linéaire* sur les données $(x_j)_{j=1,\dots, m}$ est de la forme:
$$
\begin{align}
opt(x)=& \sum_{j=1}^n c_j x_j \\
\forall i\in\{1,\dots,p\},& \sum_{j=1}^n t_{i,j}x_j \geq d_i \\
\forall i\in\{p+1,\dots,m\}& \sum_{j=1}^n t_{i,j}x_j = d_i \\
\forall j\in\{1,\dots,q\}, & x_j\geq 0 
\end{align}
$$
avec:
- $(c_j)_{j=1,\dots, n}$ une suite de $n$ constantes,
- $(d_i)_{i=1,\dots, m}$ une suite de $m$ contraintes,
-  $(t_{i,j})_{i\in\{1,\dots,m\},j\in\{1,\dots,n\}}$ une suite de nombre réels appelés *coefficients technologiques*,
-  enfin $q$ et $p$ sont deux entiers entre $1$ et $n$.

La quantité à optimiser *opt* est appelée la *fonction objectif*, les dernières contraintes sont des *contraintes de positivités* et les autres sont des *contraintes réelles.*

*Remarque:* dans l'équation ci-dessus une contrainte exprimée avec $\geq$ peut-être exprimée avec $\leq$ en multipliant l'équation par $-1$.

En utilisant des notations vectorielles, on a:
$$
\begin{align}
opt=& c\cdot x \\
\forall i\in\{1,\dots,p\}, & \tau_i\cdot x \leq d_i \\
\forall i\in\{p+1,\dots,m\}, & \tau_i\cdot x = d_i \\
\forall j\in\{1,\dots,q\}, & x_j\geq 0 
\end{align}
$$
en posant:
$$
\begin{align*}
x=\begin{pmatrix}
x_1 \\
\vdots \\
x_n
\end{pmatrix}, c=(c_1,\dots,c_n), d=(d_1,\dots, d_m), T=(t_{i,j})_{\substack{i=1,\dots, m \\ j=1,\dots, n}}, \tau_i=(t_{i,1},\dots,t_{i,n}), t_j=(t_{1,j},\dots, t_{m,j}).
\end{align*}
$$
Dans ce contexte, on appelle $T$ *matrice technologique*.

On supposera que l'optimisation à réaliser est toujours une *minimisation*. 

En effectuant des manipulations élémentaires, un problème de programmation linéaire admet deux formes.

*Remarque:* en dédoublant les variables, on peut toujours supposer que les variables sont toujours positives:
$$
x=x^+-x^- \text{ avec } x^+ \geq 0 \text{ et } x^-\geq 0.
$$

## 2.A. Différentes formulations
### 2.A.1 La formulation standard

La *formulation standard* permet d'écrire un problème de programmation linéaire en utilisant uniquement des égalités.

Pour ce faire on remplace les conditions $\leq$ avec des $=$ en introduisant des *variables d'écart*:
$$
\tau_i\cdot x\leq d_i \leftrightarrow \tau_i\cdot x_i - x_i^e=d_i \text{ et } x_i^e\geq 0.
$$
Ainsi, on peut réécrire le problème avec:
$$
\begin{align}
\min z=& c\cdot x \\
T\cdot x&=d \\
x\geq 0
\end{align}
$$

### 2.A.2 Le formulation canonique

Les cas $=$ peuvent être écrits grâce à deux symboles  $\geq$ comme suit:
$$
\tau_i\cdot x \leftrightarrow \begin{cases}
-\tau_i\cdot x \geq -d_i, \\
\tau_i\cdot x \geq d_i.
\end{cases}
$$

Ainsi, quitte à dédoubler les contraintes, on peut toujours écrire le programme linéaire sous la forme suivante:
$$
\begin{align}
\min z=& c\cdot x \\
T\cdot x&\geq d \\
x\geq 0
\end{align}
$$

## 2.B. Un exemple en variable continue

### 2.B.1. Cas continu

Les problèmes de programmation linéaire apparaissent dans différents domaines de la vie courante: en économie, pour optimiser une production, pour créer des mélanges, pour optimiser un système de transport...

But: minimiser une quantité sur les variables $x_1$ et $x_2$ en respectant les contraintes.

Prenons par exemple $c_1=4,c_2=6$, $d_1=13$ et $d_2=11$, puis comme conditions technologiques:
$$
T=\begin{pmatrix}
4 & 7 \\
3 & 6
\end{pmatrix}
$$
Considérons le problème de programmation linéaire suivant:
$$
\begin{align}
\max( & 4\cdot x_1+6\cdot x_2) \\
& 2\cdot x_1 + 2\cdot x_2 \leq 13 \\
& 2\cdot x_1 + 4\cdot x_2 \leq 19 \\
& x_i \geq 0.
\end{align}
$$


**TODO**: Représenter l'espace de recherche avec la librairie *matplotblib*.

In [21]:
import matplotlib.pyplot as plt
import numpy as np

Remarquez que cela dessine un *polygone*. Ceci arrive toujours dans le cas de problème de programmation linéaire. Puis, nous avons le théorème suivant:

**Théorème**: La solution d'un problème de programmation linéaire est soit:
- un *sommet* du polygone obtenu;
- un *côté* du polygone;
- si le polygone n'est pas borné, il est possible qu'il n'y ait pas de solution optimale finie.

**TODO**: Faire glisser des familles de droites d'équations $y=4/6 x +c$ avec différentes valeurs de $c$. Déterminer la solution optimale à partir de cela.

In [23]:
pass

Dans l'exemple donné ci-dessus, on constate que les solutions du cas continu et du cas discret ne sont a priori pas liées. En règle générale, résoudre un porblème continue est plus facile que de résoudre un problème discret.

### 2.B.2. Comparaison avec le cas discret

Maintenant, nous souhaitons que notre solution soit à coordonnées entières. Nous verrons que la nature du problème s'en trouve drastiquement changée.

**TODO**: Représenter tous les points à coordonnées entières éligible pour résoudre le problème. Une fois cela fait, utiliser la méthode graphique vue précédemment pour trouver le point optimal.

In [25]:
pass

Dans un cadre plus général, le nombre de sommets du polygone obtenu augmente en fonction des contraintes à appliquer. Leur multitude ne permet pas de visister tous ces sommets directement. Il sera donc nécessaire d'avoir recours à une stratégie plus fine comme celle donnée dans l'*algorithme du simplexe*.

## 2.B Le problème du flot maximal

Le *problème du flot maximal* sur un graphe est un problème pouvant être interprété comme un problème de programmation linéaire.

On travaille généralement avec des graphes que nous appelons *réseau de transport*, ce sont des graphes orientés avec une *source* et un *puits* vérifiant:
- la source n'a pas de prédecesseurs;
- le puits n'a pas de successeurs;
- tout sommet du graphe est accessible à partir de la source;
- tout sommet du graphe admet un chemin jusqu'au puits.

### 2.B.1 Qu'est ce que c'est ?

Considérons le graphe suivant:

![image](graphe_oriented.png)

Ce graphe peut représenter un système hydraulique. Imaginons qu'il y ait un château d'eau au noeud 1 et que nous souhaitons amener un maximum d'eau sur un autre noeud de du graphe. Les décorations sur les arêtes du graphe représente une *capacité de transport* d'une canalisation. Le problème que l'on se pose est le suivant: "Quelle configuration faut-il adopter pour amener une quantité maximale d'eau en un point donné ?"

Ce problème s'appelle la recherche de *flot maximal*.

### 2.B.2 Point de vue de la programmation linéaire en variables entières

Numérotons de $1$ à $n$ les sommets du graphe, puis identifions les poids des arcs $(i,j)$ du graphe avec une quantité $c_{i,j}$. 

Notons $\varphi_{i,j}$ le *flot* à faire passer dans l'arc $(i,j)$. Pour tout arc $(i,j)$, nous avons une contrainte à respecter: $\varphi_{i,j}\leq c_{i,j}$ plus une contrainte physique du type loi de conservation de la matière.

Pour tout $i\in\{1,\dots,n\}$, notons $\Gamma^-(i)$ l'ensemble des *prédecesseurs* du noeud $i$ et $\Gamma^+(i)$ l'ensemble de ses *successeurs*.

Du point de vue de la programmation linéaire, la recherche du *flot maximal* de $1$ vers $C$ revient à résoudre le problème suivant:
$$
\begin{align*}
opt(\varphi)&= \sum_{i\in\Gamma^-(C)} \varphi_{i,C} \\
\forall (i,j)\in\{1,\dots,n\}^2, &\varphi_{i,j}\leq c_{i,j} \\
\forall i\in\{2,\dots,n\}, & \sum_{j_-\in \Gamma^-(i)} \varphi_{j_-,i}=\sum_{j_+ \in \Gamma^+(i,j_+)} \varphi(i,j_+) \\
\varphi_{i,j}&\in\mathbb{N}.
\end{align*}
$$

On peut s'intéresser au problème du flot maximal en considérant le réseau de transport dans ce graphe de source $1$ et de puits $6$. 

**TODO**: Programmer une fonction *is_flot(flot,G,s,p)* où $s$ est la source du réseau et $p$ le puits, $G$ est la matrice du graphe, qui vérifie si la matrice des *flots* désigne bien un flot de la source $s$ vers la cible $p$ respectant les contraintes de conservation.  

In [27]:
def is_flot(flot,G,s,p):
   pass

In [51]:
flot=np.array([[0,0,0,0,2,5,0],[0,0,0,0,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,2,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
is_flot(flot, B , 0, 5)

False

In [53]:
flot=np.array([[0,0,0,0,4,5,0],[0,0,0,0,0,0,0],[0,0,0,0,0,2,0],[0,0,0,0,0,0,0],[0,0,2,0,0,2,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
is_flot(flot, B , 0, 5)

False

In [55]:
flot=np.array([[0,0,0,0,2,5,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,2,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0]])
is_flot(flot, B , 0, 5)

True

Considérons une arête d'un réseau de transport $G$ et un flot $\varphi$ sur $G$. On dit qu'une arête $(i,j)$ du graphe $G$ est *saturé* si la capacité de cette arête est égale à $\varphi_{(i,j)}$.

Etant donné un flot $\varphi$ sur un réseau de transport $G$, on peut définir le *graphe des écarts* associé au flot $\varphi$ comme suit:
- le graphe des écarts sera noté $G^e$:
- il a les mêmes sommets que $G$;
- l'ensemble de ses arêtes $E(G)$ est constitué des arêtes $(i,j)$ de $G$ qui sont non-saturées par le flot $\varphi$. De plus, leurs capacités est donnée par $c_{(i,j)}-\varphi_{i,j}$.

**TODO**: Donner une fonction *graphe_ecart(G,F)* qui à partir de la matrice d'adjacence du graphe $G$ et du flot $F$ détermine la matrice d'adjacence du graphe des écarts de $G$ pour le flot $F$.

In [29]:
 def graphe_ecart(G,F):
     pass
graphe_ecart(B,flot)

NameError: name 'B' is not defined

Grâce à un parcours en profondeur, on cherche les chemins reliant la source au puits dans le graphe des écarts.

**Remarque:** pour ceux qui en aurait entendu parler auparavant, cette démarche est analogue à la recherche de *chaînes augmentantes*. 

**TODO**: Coder une fonction *chemin(G,s,p)* qui étant donnée la matrice d'adjacence du graphe $G$, recherche un chemin (avec le plus grand poids de façon à vérifier une loi de censervation sur le chemin) allant de $s$ à $p$. Il renvoie un chemin si cela existe sinon il renvoie le booléen *False*.

In [31]:
def chemin(G,s,p):
    pass

In [63]:
print(B)
chemin(B,0,5)

[[ 0  5  0  3 12  5  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  0  0 16  0]
 [ 0  0  0  0  1  0  1]
 [ 0  0  1  0  0  2  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]


([0, 1, 3, 4, 2, 5], 1)

In [65]:
chemin(B,6,5)

False

Pour résoudre le problème de la recherche du flot maximal, nous utilisons le théorème suivant:

**Théorème**: Soit $G$ un réseau de transport de source $s$ et de puit $p$. Considérons $\varphi$ un flot sur $G$. Alors:
$$ 
\varphi \text{ est un flot maximal } \iff \text{ il n'y a pas de chemin de s à p dans le graphe d'écart.}
$$

Par conséquent, cela nous donne un algorithme pour résoudre le problème de la recherche d'un flot maximal:
- partir d'un flot initial $\varphi_0$ (que l'on pourra choisir nul);
- calculer le graphe d'écart;
- rechercher un chemin de $s$ à $p$ dans le graphe d'écart;
- si cela n'existe pas, on a trouvé un flot maximal.
- sinon, on trouve un chemin *ch* de $s$ à $p$ dans le graphe d'écart $G^e$. On génère un nouveau flot $\varphi_{n+1}$ à partir de $\varphi_n$ en posant:
$$
\varphi^{k+1}_{(i,j)}=\varphi^{k}_{(i,j)}+ch_{(i,j)}.
$$
où $ch_{(i,j)}$ est le poids de l'arête $(i,j)$ dans le chemin $ch$ du graphe d'écart. Puis, on reprends les étapes précédentes jusqu'à ce qu'il n'y ait plus de chemin de $s$ à $p$ dans le graphe d'écart.

Cet algorithme s'appelle l'agorithme de *Ford-Fulkerson*.

**Remarque**: on peut aussi adapter cette démarche lorsque les arêtes ont des capacités minimales (on doit faire passer une quantité minimale dans chacune).

**TODO**: Programmer une procédure *Ford_Fulkerson(G,s,p)* qui recherche un flot maximal de $s$ à $p$ dans le graphe $G$.

In [33]:
def Ford_Fulkerson(G,s,p):
    pass

In [84]:
Ford_Fulkerson(B,0,5)

array([[0., 1., 0., 0., 2., 5., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 3. Différents problèmes classiques

## 3.A. Le problème de l'arbre couvrant minimal

Considérons un graphe *connexe* $G$.
On cherche l'objet suivant:
- un arbre
- passant par tous les sommets (dit *couvrant*)
- de poids total *minimal*

On appelle ce dernier *l'arbre couvrant minimal*.

**TODO**: code une fonction *is_covering(M,T)* où $M$ est la matrice d'adjacence de $G$, $T$ la matrice d'adjacence du sous-graphe renvoyant un booléen en fonction de si $T$ est un arbre couvrant de $T$. Dans le cas où la réponse est affirmative, retourner le poids de l'arbre. 

In [35]:
def is_covering(M,T):
    pass

In [89]:
A=np.array([[0,4,0,0,6,0,0],[4,0,2,3,0,0,0],[0,2,0,11,0,0,0],[0,3,11,0,7,0,0],[6,0,0,7,0,7,4],[0,0,0,0,7,0,5],[0,0,0,0,4,5,0]])
T=np.array([[0,4,0,0,0,0,0],[4,0,0,3,0,0,0],[0,0,0,11,0,0,0],[0,3,11,0,7,0,0],[0,0,0,7,0,7,4],[0,0,0,0,7,0,0],[0,0,0,0,4,0,0]])
is_covering(A,T)

36.0

In [93]:
A=np.array([[0,4,0,0,6,0,0],[4,0,2,3,0,0,0],[0,2,0,11,0,0,0],[0,3,11,0,7,0,0],[6,0,0,7,0,7,4],[0,0,0,0,7,0,5],[0,0,0,0,4,5,0]])
T=np.array([[0,4,0,0,6,0,0],[4,0,0,3,0,0,0],[0,0,0,11,0,0,0],[0,3,11,0,7,0,0],[0,0,0,7,0,7,4],[0,0,0,0,7,0,0],[0,0,0,0,4,0,0]])
is_covering(A,T)

False


## 3.B. Le problème du voyageur de commerce

On considère un graphe $G$. Le but est de trouver une *chaîne hamiltonienne*, c'est-à-dire un cycle passant une et une seule fois par chaque sommet du graphe de poids minimal.

Ceci est le cas lorsqu'un commercial souhaite faire sa tournée nationale dans différente ville en minimisant la distance parcourue ou le temps de parcours.

**TODO**: Etant donné la matrice d'adjacence d'un graphe $G$ et $L$ la liste des sommets visités par un chemin, coder une fonction *is_hamilt(G,L)* qui vérifie si $L$ est un cycle hamiltonien de $G$. Dans l'affirmative, retourner le poids de la chaîne hamiltonienne.

In [37]:
def is_hamilt(G,L):
    pass

In [115]:
A=np.array([[0,4,0,0,6,0,0],[4,0,2,3,0,0,0],[0,2,0,11,0,0,0],[0,3,11,0,7,0,0],[6,0,0,7,0,7,4],[0,0,0,0,7,0,5],[0,0,0,0,4,5,0]])
C=[0,1,2,3,4,0]
is_hamilt(A,C)

False

## 3.C Le problème du sac à dos

Vous souhaitez partir en randonnée dans la montagne pour plusieurs jours. Vous devez donc préparer votre sac avec des provisions.
Vous pouvez porter qu'un poids maximal *Max* et vous avez une liste d'ingrédients disponibles avec chacun un poids *P*, une disponibilité de $Q$ et une valeur nutritionnelle *VN*. 

Le but de ce problème est de composer un sac avec une valeur nutritionnelle maximale.

Par exemple, on peut considérer un sac de contenance maximale $13$ et:
$$
\begin{array}{c|ccc}
     & A & B & C \\
 Q& 2 & 2 & 2 \\
 P   &  5 & 4 & 3 \\
 VN  & 10 & 6 & 3
 \end{array}
$$

On pourra représenter une solution de ce problème comme une liste:
$$
L=[x_A,x_B,x_C]
$$

**TODO**: Etant donné la matrice du problème comme donnée ci-dessus $M$, coder une fonction *sol_sac(M,L)* qui vérifie renvoie True  si la liste est une solution du problème ainsi que la valeur nutritionnelle du sac, sinon retourne False. Tester votre fonction avec l'exemple précédent.

In [126]:
M=np.array([[2,2,2],[5,4,3],[10,6,3]])

In [39]:
def sol_sac(M,L,max_poids):
    pass

In [138]:
sol_sac(M,[2,0,1],13)

(True, 23)

**TODO**: Effectuer la résolution graphique de ce problème.

### 3.D. L'algorithme glouton

Pour résoudre ces problèmes, nous pouvons utiliser une méthode dite *gloutonne* qui consiste à faire le meilleur choix à l'instant présent. Concrètement pour chacun des problèmes précédents cela donne:
- **le problème de l'arbre couvrant minimal:** on choisit l'arête admissible la moins chère qui ne crée pas de cycle.
- **le problème du voyageur de commerce**: on choisit l'arête la moins chère qui ne forme pas de cycle et tel que les sommets restent de degré inférieur à $2$.
- **le problème du sac à dos**: on choisit l'aliment disponible qui le meilleur rapport *VN/poids*.

**TODO**: Coder les algorithmes gloutons pour chacun de ces problèmes. Tester les sur les exemples précédents puis évaluer leurs complexités.

*Remarque:* pour ce faire nous allons trier les arêtes du graphe par leur poids et choisir la meilleure option de manière à obtenir un arbre.

In [41]:
def glouton_couvrant(M):
    pass

In [183]:
def glouton_commerce(M):
    pass

In [ ]:
def glouton_sac(M):
    pass

*Remarque*: dans le cas de l'arbre couvrant l'algorithme glouton s'appelle l'algorithme de Kruskal. Ce dernier fournit toujours la solution optimale dans pour ce problème.